# Generated by Django 3.0 on 2021-07-16 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_trip_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='participants',
            new_name='travelers',
        ),
    ]
