# Generated by Django 3.0 on 2021-07-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210716_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
